#:schema node_modules/wrangler/config-schema.json
name = "ozan"
compatibility_date = "2024-10-18"
pages_build_output_dir = ".svelte-kit/cloudflare"
[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "ozan"
database_id = "7e737df2-edac-446c-a1fd-44ad2a7530fd"
